services:
  terrano-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terrano-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: terrano
      DB_USER: terrano
      DB_PASS: admin
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - terrano-network

  db:
    image: mysql:8.0.45-bookworm
    container_name: terrano-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "${DB_NAME:-terrano-api}"
      MYSQL_USER: "${DB_USER:-terrano-api}"
      MYSQL_PASSWORD: "${DB_PASS:-terrano-api}"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - terrano-network

volumes:
  mysql-data:
    name: mysql-data
    driver: local

networks:
  terrano-network:
    name: terrano-network
    driver: bridge
