services:
  terrano-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terrano-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
      JWT_SECRET: asedsadsaeweew
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - terrano-network

networks:
  terrano-network:
    name: terrano-network
    driver: bridge