import { MigrationInterface, QueryRunner } from "typeorm";

export class AdjustMovementTables1780264709775 implements MigrationInterface {
    name = 'AdjustMovementTables1780264709775'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_purchase_item_purchase"`);
        await queryRunner.query(`DROP INDEX "IDX_purchase_item_product"`);
        await queryRunner.query(`CREATE TABLE "temporary_purchase_item" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "quantity" real NOT NULL, "unit_price" real NOT NULL, "total" real NOT NULL, "product_id" integer, "purchase_id" integer)`);
        await queryRunner.query(`INSERT INTO "temporary_purchase_item"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "quantity", "unit_price", "total", "product_id", "purchase_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "quantity", "unit_price", "total", "product_id", "purchase_id" FROM "purchase_item"`);
        await queryRunner.query(`DROP TABLE "purchase_item"`);
        await queryRunner.query(`ALTER TABLE "temporary_purchase_item" RENAME TO "purchase_item"`);
        await queryRunner.query(`CREATE INDEX "IDX_purchase_item_purchase" ON "purchase_item" ("purchase_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_purchase_item_product" ON "purchase_item" ("product_id") `);
        await queryRunner.query(`DROP INDEX "IDX_purchase_supplier"`);
        await queryRunner.query(`CREATE TABLE "temporary_purchase" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "nf_number" varchar(50), "nf_serie" varchar(50), "total" real NOT NULL DEFAULT (0), "used_nf_xml_document" boolean NOT NULL DEFAULT (0), "internal_notes" text, "purchase_date" date NOT NULL, "estimated_delivery_date" date, "supplier_id" integer)`);
        await queryRunner.query(`INSERT INTO "temporary_purchase"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "nf_number", "nf_serie", "total", "used_nf_xml_document", "internal_notes", "purchase_date", "estimated_delivery_date", "supplier_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "nf_number", "nf_serie", "total", "used_nf_xml_document", "internal_notes", "purchase_date", "estimated_delivery_date", "supplier_id" FROM "purchase"`);
        await queryRunner.query(`DROP TABLE "purchase"`);
        await queryRunner.query(`ALTER TABLE "temporary_purchase" RENAME TO "purchase"`);
        await queryRunner.query(`CREATE INDEX "IDX_purchase_supplier" ON "purchase" ("supplier_id") `);
        await queryRunner.query(`DROP INDEX "IDX_purchase_payment_purchase"`);
        await queryRunner.query(`CREATE TABLE "temporary_purchase_payment" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "total" real NOT NULL, "payment_method" varchar NOT NULL, "purchase_id" integer)`);
        await queryRunner.query(`INSERT INTO "temporary_purchase_payment"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "total", "payment_method", "purchase_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "total", "payment_method", "purchase_id" FROM "purchase_payment"`);
        await queryRunner.query(`DROP TABLE "purchase_payment"`);
        await queryRunner.query(`ALTER TABLE "temporary_purchase_payment" RENAME TO "purchase_payment"`);
        await queryRunner.query(`CREATE INDEX "IDX_purchase_payment_purchase" ON "purchase_payment" ("purchase_id") `);
        await queryRunner.query(`DROP INDEX "IDX_purchase_item_purchase"`);
        await queryRunner.query(`DROP INDEX "IDX_purchase_item_product"`);
        await queryRunner.query(`DROP INDEX "IDX_purchase_supplier"`);
        await queryRunner.query(`DROP INDEX "IDX_purchase_payment_purchase"`);
        await queryRunner.query(`CREATE TABLE "movement_entry" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "entry_date" datetime NOT NULL, "entry_movement_category" varchar CHECK( "entry_movement_category" IN ('PURCHASE','ADJUSTMENT') ) NOT NULL, "purchase_id" integer)`);
        await queryRunner.query(`CREATE TABLE "movement_exit" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "exit_date" datetime NOT NULL, "exit_movement_category" varchar CHECK( "exit_movement_category" IN ('MATERIAL_REQUEST','STOCK_LOCATION_TRANSFER','DEFECTIVE','RETURN','ADJUSTMENT') ) NOT NULL, "purchase_id" integer, "stock_requisition_id" integer)`);
        await queryRunner.query(`CREATE TABLE "movement" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "quantity" integer NOT NULL, "product_id" integer, "movement_exit_id" integer, "movement_entry_id" integer, "stock_location_id" integer)`);
        await queryRunner.query(`CREATE TABLE "temporary_purchase_item" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "quantity" real NOT NULL, "unit_price" real NOT NULL, "total" real NOT NULL, "product_id" integer, "purchase_id" integer, CONSTRAINT "FK_f8ebd7fa6b8adf0360ee5b547ff" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_350d9b7c4792561317ca3a37e1d" FOREIGN KEY ("purchase_id") REFERENCES "purchase" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_purchase_item"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "quantity", "unit_price", "total", "product_id", "purchase_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "quantity", "unit_price", "total", "product_id", "purchase_id" FROM "purchase_item"`);
        await queryRunner.query(`DROP TABLE "purchase_item"`);
        await queryRunner.query(`ALTER TABLE "temporary_purchase_item" RENAME TO "purchase_item"`);
        await queryRunner.query(`CREATE TABLE "temporary_purchase" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "nf_number" varchar(50), "nf_serie" varchar(50), "total" real NOT NULL DEFAULT (0), "used_nf_xml_document" boolean NOT NULL DEFAULT (0), "internal_notes" text, "purchase_date" date NOT NULL, "estimated_delivery_date" date, "supplier_id" integer, CONSTRAINT "FK_8d9a856657c46725d085c73e4fc" FOREIGN KEY ("supplier_id") REFERENCES "supplier" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_purchase"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "nf_number", "nf_serie", "total", "used_nf_xml_document", "internal_notes", "purchase_date", "estimated_delivery_date", "supplier_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "nf_number", "nf_serie", "total", "used_nf_xml_document", "internal_notes", "purchase_date", "estimated_delivery_date", "supplier_id" FROM "purchase"`);
        await queryRunner.query(`DROP TABLE "purchase"`);
        await queryRunner.query(`ALTER TABLE "temporary_purchase" RENAME TO "purchase"`);
        await queryRunner.query(`CREATE TABLE "temporary_movement_entry" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "entry_date" datetime NOT NULL, "entry_movement_category" varchar CHECK( "entry_movement_category" IN ('PURCHASE','ADJUSTMENT') ) NOT NULL, "purchase_id" integer, CONSTRAINT "FK_21657f0868ba844d4d9f655aa58" FOREIGN KEY ("purchase_id") REFERENCES "purchase" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_movement_entry"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "entry_date", "entry_movement_category", "purchase_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "entry_date", "entry_movement_category", "purchase_id" FROM "movement_entry"`);
        await queryRunner.query(`DROP TABLE "movement_entry"`);
        await queryRunner.query(`ALTER TABLE "temporary_movement_entry" RENAME TO "movement_entry"`);
        await queryRunner.query(`CREATE TABLE "temporary_movement_exit" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "exit_date" datetime NOT NULL, "exit_movement_category" varchar CHECK( "exit_movement_category" IN ('MATERIAL_REQUEST','STOCK_LOCATION_TRANSFER','DEFECTIVE','RETURN','ADJUSTMENT') ) NOT NULL, "purchase_id" integer, "stock_requisition_id" integer, CONSTRAINT "FK_88c19e8e096e62cb5eca8566110" FOREIGN KEY ("purchase_id") REFERENCES "purchase" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_ea2cb4ba7c29001704d5effc01d" FOREIGN KEY ("stock_requisition_id") REFERENCES "stock_requisition" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_movement_exit"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "exit_date", "exit_movement_category", "purchase_id", "stock_requisition_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "exit_date", "exit_movement_category", "purchase_id", "stock_requisition_id" FROM "movement_exit"`);
        await queryRunner.query(`DROP TABLE "movement_exit"`);
        await queryRunner.query(`ALTER TABLE "temporary_movement_exit" RENAME TO "movement_exit"`);
        await queryRunner.query(`CREATE TABLE "temporary_movement" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "quantity" integer NOT NULL, "product_id" integer, "movement_exit_id" integer, "movement_entry_id" integer, "stock_location_id" integer, CONSTRAINT "FK_04fb7658224d6ceadd8e400283e" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f14eef4d85fac2d2f3c468c1d03" FOREIGN KEY ("movement_exit_id") REFERENCES "movement_exit" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_afe0cc7fc39e8e208ead0feab52" FOREIGN KEY ("movement_entry_id") REFERENCES "movement_entry" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_8f4ad02a548c9d87ab80b9cc36e" FOREIGN KEY ("stock_location_id") REFERENCES "stock_location" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_movement"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "quantity", "product_id", "movement_exit_id", "movement_entry_id", "stock_location_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "quantity", "product_id", "movement_exit_id", "movement_entry_id", "stock_location_id" FROM "movement"`);
        await queryRunner.query(`DROP TABLE "movement"`);
        await queryRunner.query(`ALTER TABLE "temporary_movement" RENAME TO "movement"`);
        await queryRunner.query(`CREATE TABLE "temporary_purchase_payment" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "total" real NOT NULL, "payment_method" varchar NOT NULL, "purchase_id" integer, CONSTRAINT "FK_2b4700cd746d17ea22e37cd30d7" FOREIGN KEY ("purchase_id") REFERENCES "purchase" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_purchase_payment"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "total", "payment_method", "purchase_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "total", "payment_method", "purchase_id" FROM "purchase_payment"`);
        await queryRunner.query(`DROP TABLE "purchase_payment"`);
        await queryRunner.query(`ALTER TABLE "temporary_purchase_payment" RENAME TO "purchase_payment"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "purchase_payment" RENAME TO "temporary_purchase_payment"`);
        await queryRunner.query(`CREATE TABLE "purchase_payment" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "total" real NOT NULL, "payment_method" varchar NOT NULL, "purchase_id" integer)`);
        await queryRunner.query(`INSERT INTO "purchase_payment"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "total", "payment_method", "purchase_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "total", "payment_method", "purchase_id" FROM "temporary_purchase_payment"`);
        await queryRunner.query(`DROP TABLE "temporary_purchase_payment"`);
        await queryRunner.query(`ALTER TABLE "movement" RENAME TO "temporary_movement"`);
        await queryRunner.query(`CREATE TABLE "movement" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "quantity" integer NOT NULL, "product_id" integer, "movement_exit_id" integer, "movement_entry_id" integer, "stock_location_id" integer)`);
        await queryRunner.query(`INSERT INTO "movement"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "quantity", "product_id", "movement_exit_id", "movement_entry_id", "stock_location_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "quantity", "product_id", "movement_exit_id", "movement_entry_id", "stock_location_id" FROM "temporary_movement"`);
        await queryRunner.query(`DROP TABLE "temporary_movement"`);
        await queryRunner.query(`ALTER TABLE "movement_exit" RENAME TO "temporary_movement_exit"`);
        await queryRunner.query(`CREATE TABLE "movement_exit" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "exit_date" datetime NOT NULL, "exit_movement_category" varchar CHECK( "exit_movement_category" IN ('MATERIAL_REQUEST','STOCK_LOCATION_TRANSFER','DEFECTIVE','RETURN','ADJUSTMENT') ) NOT NULL, "purchase_id" integer, "stock_requisition_id" integer)`);
        await queryRunner.query(`INSERT INTO "movement_exit"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "exit_date", "exit_movement_category", "purchase_id", "stock_requisition_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "exit_date", "exit_movement_category", "purchase_id", "stock_requisition_id" FROM "temporary_movement_exit"`);
        await queryRunner.query(`DROP TABLE "temporary_movement_exit"`);
        await queryRunner.query(`ALTER TABLE "movement_entry" RENAME TO "temporary_movement_entry"`);
        await queryRunner.query(`CREATE TABLE "movement_entry" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "entry_date" datetime NOT NULL, "entry_movement_category" varchar CHECK( "entry_movement_category" IN ('PURCHASE','ADJUSTMENT') ) NOT NULL, "purchase_id" integer)`);
        await queryRunner.query(`INSERT INTO "movement_entry"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "entry_date", "entry_movement_category", "purchase_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "entry_date", "entry_movement_category", "purchase_id" FROM "temporary_movement_entry"`);
        await queryRunner.query(`DROP TABLE "temporary_movement_entry"`);
        await queryRunner.query(`ALTER TABLE "purchase" RENAME TO "temporary_purchase"`);
        await queryRunner.query(`CREATE TABLE "purchase" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "nf_number" varchar(50), "nf_serie" varchar(50), "total" real NOT NULL DEFAULT (0), "used_nf_xml_document" boolean NOT NULL DEFAULT (0), "internal_notes" text, "purchase_date" date NOT NULL, "estimated_delivery_date" date, "supplier_id" integer)`);
        await queryRunner.query(`INSERT INTO "purchase"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "nf_number", "nf_serie", "total", "used_nf_xml_document", "internal_notes", "purchase_date", "estimated_delivery_date", "supplier_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "nf_number", "nf_serie", "total", "used_nf_xml_document", "internal_notes", "purchase_date", "estimated_delivery_date", "supplier_id" FROM "temporary_purchase"`);
        await queryRunner.query(`DROP TABLE "temporary_purchase"`);
        await queryRunner.query(`ALTER TABLE "purchase_item" RENAME TO "temporary_purchase_item"`);
        await queryRunner.query(`CREATE TABLE "purchase_item" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "quantity" real NOT NULL, "unit_price" real NOT NULL, "total" real NOT NULL, "product_id" integer, "purchase_id" integer)`);
        await queryRunner.query(`INSERT INTO "purchase_item"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "quantity", "unit_price", "total", "product_id", "purchase_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "quantity", "unit_price", "total", "product_id", "purchase_id" FROM "temporary_purchase_item"`);
        await queryRunner.query(`DROP TABLE "temporary_purchase_item"`);
        await queryRunner.query(`DROP TABLE "movement"`);
        await queryRunner.query(`DROP TABLE "movement_exit"`);
        await queryRunner.query(`DROP TABLE "movement_entry"`);
        await queryRunner.query(`CREATE INDEX "IDX_purchase_payment_purchase" ON "purchase_payment" ("purchase_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_purchase_supplier" ON "purchase" ("supplier_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_purchase_item_product" ON "purchase_item" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_purchase_item_purchase" ON "purchase_item" ("purchase_id") `);
        await queryRunner.query(`DROP INDEX "IDX_purchase_payment_purchase"`);
        await queryRunner.query(`ALTER TABLE "purchase_payment" RENAME TO "temporary_purchase_payment"`);
        await queryRunner.query(`CREATE TABLE "purchase_payment" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "total" real NOT NULL, "payment_method" varchar NOT NULL, "purchase_id" integer, CONSTRAINT "FK_purchase_payment_purchase" FOREIGN KEY ("purchase_id") REFERENCES "purchase" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "purchase_payment"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "total", "payment_method", "purchase_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "total", "payment_method", "purchase_id" FROM "temporary_purchase_payment"`);
        await queryRunner.query(`DROP TABLE "temporary_purchase_payment"`);
        await queryRunner.query(`CREATE INDEX "IDX_purchase_payment_purchase" ON "purchase_payment" ("purchase_id") `);
        await queryRunner.query(`DROP INDEX "IDX_purchase_supplier"`);
        await queryRunner.query(`ALTER TABLE "purchase" RENAME TO "temporary_purchase"`);
        await queryRunner.query(`CREATE TABLE "purchase" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "nf_number" varchar(50), "nf_serie" varchar(50), "total" real NOT NULL DEFAULT (0), "used_nf_xml_document" boolean NOT NULL DEFAULT (0), "internal_notes" text, "purchase_date" date NOT NULL, "estimated_delivery_date" date, "supplier_id" integer, CONSTRAINT "FK_purchase_supplier" FOREIGN KEY ("supplier_id") REFERENCES "supplier" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "purchase"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "nf_number", "nf_serie", "total", "used_nf_xml_document", "internal_notes", "purchase_date", "estimated_delivery_date", "supplier_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "nf_number", "nf_serie", "total", "used_nf_xml_document", "internal_notes", "purchase_date", "estimated_delivery_date", "supplier_id" FROM "temporary_purchase"`);
        await queryRunner.query(`DROP TABLE "temporary_purchase"`);
        await queryRunner.query(`CREATE INDEX "IDX_purchase_supplier" ON "purchase" ("supplier_id") `);
        await queryRunner.query(`DROP INDEX "IDX_purchase_item_product"`);
        await queryRunner.query(`DROP INDEX "IDX_purchase_item_purchase"`);
        await queryRunner.query(`ALTER TABLE "purchase_item" RENAME TO "temporary_purchase_item"`);
        await queryRunner.query(`CREATE TABLE "purchase_item" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "quantity" real NOT NULL, "unit_price" real NOT NULL, "total" real NOT NULL, "product_id" integer, "purchase_id" integer, CONSTRAINT "FK_purchase_item_purchase" FOREIGN KEY ("purchase_id") REFERENCES "purchase" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_purchase_item_product" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "purchase_item"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "quantity", "unit_price", "total", "product_id", "purchase_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "quantity", "unit_price", "total", "product_id", "purchase_id" FROM "temporary_purchase_item"`);
        await queryRunner.query(`DROP TABLE "temporary_purchase_item"`);
        await queryRunner.query(`CREATE INDEX "IDX_purchase_item_product" ON "purchase_item" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_purchase_item_purchase" ON "purchase_item" ("purchase_id") `);
    }

}
