import { MigrationInterface, QueryRunner } from "typeorm";

export class Policies1781383972002 implements MigrationInterface {
    name = 'Policies1781383972002'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_stock_requisition_status_log" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "previous_status" varchar, "current_status" varchar NOT NULL, "change_justification" varchar(255), "stock_requisition_id" integer, CONSTRAINT "FK_46ae982e423904ac78fea11bfff" FOREIGN KEY ("stock_requisition_id") REFERENCES "stock_requisition" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_stock_requisition_status_log"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "previous_status", "current_status", "change_justification", "stock_requisition_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "previous_status", "current_status", "change_justification", "stock_requisition_id" FROM "stock_requisition_status_log"`);
        await queryRunner.query(`DROP TABLE "stock_requisition_status_log"`);
        await queryRunner.query(`ALTER TABLE "temporary_stock_requisition_status_log" RENAME TO "stock_requisition_status_log"`);
        await queryRunner.query(`CREATE TABLE "temporary_policy" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "name" varchar(100) NOT NULL, "description" text, "resource" varchar(50) NOT NULL, "action" varchar(50) NOT NULL, "module" varchar(50) NOT NULL, CONSTRAINT "UQ_5ad65e4ff971649343992959bd0" UNIQUE ("name"))`);
        await queryRunner.query(`INSERT INTO "temporary_policy"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "name", "description", "resource", "action") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "name", "description", "resource", "action" FROM "policy"`);
        await queryRunner.query(`DROP TABLE "policy"`);
        await queryRunner.query(`ALTER TABLE "temporary_policy" RENAME TO "policy"`);
        await queryRunner.query(`CREATE TABLE "temporary_user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "name" varchar(100) NOT NULL, "phone" varchar(20), "cpf" varchar(14), "email" varchar(300) NOT NULL, "username" varchar(50) NOT NULL, "password" varchar(100) NOT NULL, "requires_password_reset" boolean NOT NULL DEFAULT (0), "password_reset_token" varchar(255), "password_reset_token_expires_at" datetime, "role_id" integer, "department_id" integer, "profile_picture" varchar(255), CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb" UNIQUE ("username"), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "FK_afd2c87bee70dd5557f48911e66" FOREIGN KEY ("department_id") REFERENCES "department" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_fb2e442d14add3cefbdf33c4561" FOREIGN KEY ("role_id") REFERENCES "role" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_user"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "name", "phone", "cpf", "email", "username", "password", "requires_password_reset", "password_reset_token", "password_reset_token_expires_at", "role_id", "department_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "name", "phone", "cpf", "email", "username", "password", "requires_password_reset", "password_reset_token", "password_reset_token_expires_at", "role_id", "department_id" FROM "user"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`ALTER TABLE "temporary_user" RENAME TO "user"`);
        await queryRunner.query(`CREATE TABLE "temporary_stock_requisition_status_log" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "previous_status" varchar, "current_status" varchar NOT NULL, "change_justification" varchar(255), "stock_requisition_id" integer)`);
        await queryRunner.query(`INSERT INTO "temporary_stock_requisition_status_log"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "previous_status", "current_status", "change_justification", "stock_requisition_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "previous_status", "current_status", "change_justification", "stock_requisition_id" FROM "stock_requisition_status_log"`);
        await queryRunner.query(`DROP TABLE "stock_requisition_status_log"`);
        await queryRunner.query(`ALTER TABLE "temporary_stock_requisition_status_log" RENAME TO "stock_requisition_status_log"`);
        await queryRunner.query(`CREATE TABLE "temporary_stock_requisition_status_log" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "previous_status" varchar, "current_status" varchar NOT NULL, "change_justification" varchar(255), "stock_requisition_id" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "temporary_stock_requisition_status_log"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "previous_status", "current_status", "change_justification", "stock_requisition_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "previous_status", "current_status", "change_justification", "stock_requisition_id" FROM "stock_requisition_status_log"`);
        await queryRunner.query(`DROP TABLE "stock_requisition_status_log"`);
        await queryRunner.query(`ALTER TABLE "temporary_stock_requisition_status_log" RENAME TO "stock_requisition_status_log"`);
        await queryRunner.query(`CREATE TABLE "temporary_stock_requisition_status_log" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "previous_status" varchar, "current_status" varchar NOT NULL, "change_justification" varchar(255), "stock_requisition_id" integer NOT NULL, CONSTRAINT "FK_46ae982e423904ac78fea11bfff" FOREIGN KEY ("stock_requisition_id") REFERENCES "stock_requisition" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_stock_requisition_status_log"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "previous_status", "current_status", "change_justification", "stock_requisition_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "previous_status", "current_status", "change_justification", "stock_requisition_id" FROM "stock_requisition_status_log"`);
        await queryRunner.query(`DROP TABLE "stock_requisition_status_log"`);
        await queryRunner.query(`ALTER TABLE "temporary_stock_requisition_status_log" RENAME TO "stock_requisition_status_log"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "stock_requisition_status_log" RENAME TO "temporary_stock_requisition_status_log"`);
        await queryRunner.query(`CREATE TABLE "stock_requisition_status_log" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "previous_status" varchar, "current_status" varchar NOT NULL, "change_justification" varchar(255), "stock_requisition_id" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "stock_requisition_status_log"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "previous_status", "current_status", "change_justification", "stock_requisition_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "previous_status", "current_status", "change_justification", "stock_requisition_id" FROM "temporary_stock_requisition_status_log"`);
        await queryRunner.query(`DROP TABLE "temporary_stock_requisition_status_log"`);
        await queryRunner.query(`ALTER TABLE "stock_requisition_status_log" RENAME TO "temporary_stock_requisition_status_log"`);
        await queryRunner.query(`CREATE TABLE "stock_requisition_status_log" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "previous_status" varchar, "current_status" varchar NOT NULL, "change_justification" varchar(255), "stock_requisition_id" integer)`);
        await queryRunner.query(`INSERT INTO "stock_requisition_status_log"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "previous_status", "current_status", "change_justification", "stock_requisition_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "previous_status", "current_status", "change_justification", "stock_requisition_id" FROM "temporary_stock_requisition_status_log"`);
        await queryRunner.query(`DROP TABLE "temporary_stock_requisition_status_log"`);
        await queryRunner.query(`ALTER TABLE "stock_requisition_status_log" RENAME TO "temporary_stock_requisition_status_log"`);
        await queryRunner.query(`CREATE TABLE "stock_requisition_status_log" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "previous_status" varchar, "current_status" varchar NOT NULL, "change_justification" varchar(255), "stock_requisition_id" integer, CONSTRAINT "FK_46ae982e423904ac78fea11bfff" FOREIGN KEY ("stock_requisition_id") REFERENCES "stock_requisition" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "stock_requisition_status_log"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "previous_status", "current_status", "change_justification", "stock_requisition_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "previous_status", "current_status", "change_justification", "stock_requisition_id" FROM "temporary_stock_requisition_status_log"`);
        await queryRunner.query(`DROP TABLE "temporary_stock_requisition_status_log"`);
        await queryRunner.query(`ALTER TABLE "user" RENAME TO "temporary_user"`);
        await queryRunner.query(`CREATE TABLE "user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "name" varchar(100) NOT NULL, "phone" varchar(20), "cpf" varchar(14), "email" varchar(300) NOT NULL, "username" varchar(50) NOT NULL, "password" varchar(100) NOT NULL, "requires_password_reset" boolean NOT NULL DEFAULT (0), "password_reset_token" varchar(255), "password_reset_token_expires_at" datetime, "role_id" integer, "department_id" integer, CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb" UNIQUE ("username"), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "FK_afd2c87bee70dd5557f48911e66" FOREIGN KEY ("department_id") REFERENCES "department" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_fb2e442d14add3cefbdf33c4561" FOREIGN KEY ("role_id") REFERENCES "role" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "user"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "name", "phone", "cpf", "email", "username", "password", "requires_password_reset", "password_reset_token", "password_reset_token_expires_at", "role_id", "department_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "name", "phone", "cpf", "email", "username", "password", "requires_password_reset", "password_reset_token", "password_reset_token_expires_at", "role_id", "department_id" FROM "temporary_user"`);
        await queryRunner.query(`DROP TABLE "temporary_user"`);
        await queryRunner.query(`ALTER TABLE "policy" RENAME TO "temporary_policy"`);
        await queryRunner.query(`CREATE TABLE "policy" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "name" varchar(100) NOT NULL, "description" text, "resource" varchar(50) NOT NULL, "action" varchar(50) NOT NULL, CONSTRAINT "UQ_5ad65e4ff971649343992959bd0" UNIQUE ("name"))`);
        await queryRunner.query(`INSERT INTO "policy"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "name", "description", "resource", "action") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "name", "description", "resource", "action" FROM "temporary_policy"`);
        await queryRunner.query(`DROP TABLE "temporary_policy"`);
        await queryRunner.query(`ALTER TABLE "stock_requisition_status_log" RENAME TO "temporary_stock_requisition_status_log"`);
        await queryRunner.query(`CREATE TABLE "stock_requisition_status_log" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "created_by" integer, "updated_by" integer, "previous_status" varchar, "current_status" varchar NOT NULL, "change_justification" varchar(255), "stock_requisition_id" integer, CONSTRAINT "FK_46ae982e423904ac78fea11bfff" FOREIGN KEY ("stock_requisition_id") REFERENCES "stock_requisition" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "stock_requisition_status_log"("id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "previous_status", "current_status", "change_justification", "stock_requisition_id") SELECT "id", "updated_at", "created_at", "deleted_at", "created_by", "updated_by", "previous_status", "current_status", "change_justification", "stock_requisition_id" FROM "temporary_stock_requisition_status_log"`);
        await queryRunner.query(`DROP TABLE "temporary_stock_requisition_status_log"`);
    }

}
